services:
  deep-research:
    container_name: deep-research
    build: .
    env_file:
      - .env.local
    # volumes:
    #   - ./:/app/  ← Закомментируйте это
    ports:
      - '3051:3051' # Проброс порта, если нужен
    tty: true
    stdin_open: true
